services:

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./inicializacion_auth_db.sql:/docker-entrypoint-initdb.d/inicializacion_auth_db.sql

  message-broker:
    image: rabbitmq:3-management
    container_name: message-broker
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  
  notification-be:
    build: ./notification-be
    container_name: notification-be
    env_file:
      - ./notification-be/.env
    depends_on:
      message-broker:
        condition: service_healthy

  prediagnostic-db:
    image: mongo
    restart: always
    container_name: prediagnostic-db
    ports:
      - "27017:27017"

  api-gateway:
    build: ./api-gateway
    container_name:  api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-db

  prediagnostic-be:
    build: ./prediagnostic-be
    container_name: prediagnostic-be
    ports:
      - "8000:8000"
    depends_on:
      - prediagnostic-db
  web-front-end:
    build: ./web-front-end
    container_name: web-front-end
    ports:
      - "3000:3000"

  auth-be:
    build: ./auth-be
    container_name: auth-be
    ports:
      - "8081:8081"

  cli-front-end:
    build: ./cli-front-end
    container_name: cli-front-end
    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]

  message-producer:
    build: ./message-producer
    container_name: message-producer
    ports:
      - "8082:8082"
    depends_on:
      message-broker:
        condition: service_healthy
      notification-be:
        condition: service_started

