networks:
  private:
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/26    # Internal services network
    internal: true                    # Ensures network isolation from external access
    labels:
      description: "Backend and Data Services Network"

  public:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24      # External access network
    labels:
      description: "Frontend Public Access Network"

services:

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./inicializacion_auth_db.sql:/docker-entrypoint-initdb.d/inicializacion_auth_db.sql
    networks:
      - private

  message-broker:
    image: rabbitmq:3-management
    container_name: message-broker
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - private
  
  notification-be:
    build: ./notification-be
    container_name: notification-be
    env_file:
      - ./notification-be/.env
    depends_on:
      message-broker:
        condition: service_healthy
    networks:
      - private

  prediagnostic-db:
    image: mongo
    restart: always
    container_name: prediagnostic-db
    ports:
      - "27017:27017"
    networks:
      - private

  api-gateway:
    build: ./api-gateway
    container_name:  api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-db
    networks:
      - private

  prediagnostic-be:
    build: ./prediagnostic-be
    container_name: prediagnostic-be
    ports:
      - "8000:8000"
    depends_on:
      - prediagnostic-db
    networks:
      - private

  web-front-end:
    build: ./web-front-end
    container_name: web-front-end
    ports:
      - "3000:3000"
    networks:
      - private
      - public

  auth-be:  
    build: ./auth-be
    container_name: auth-be
    ports:
      - "8081:8081"
    networks:
      - private

  cli-front-end:
    build: ./cli-front-end
    container_name: cli-front-end
    tty: true
    stdin_open: true
    command: ["tail", "-f", "/dev/null"]
    networks:
      - private
      - public

  message-producer:
    build: ./message-producer
    container_name: message-producer
    ports:
      - "8082:8082"
    depends_on:
      message-broker:
        condition: service_healthy
      notification-be:
        condition: service_started
    networks:
      - private
